### ISSUE TITLE
Question: Aliasing

### ISSUE THREAD

**Issue by JannikStreek** [trailblazer/representable#183]
Hi,

I have a question related to aliasing. In my current project I am kind of the middleman between an existing API and other clients (ios, android...). I would like to rename a few of the json keys that I am receiving from the other API. That works perfectly fine with the `as:` addition:

```
property :image_url, :as => :recipeUrl800x600
```

 However, when i return the json version of the object to my clients, i would like to keep the alias.

Therefore, I built a method in my domain model like this:

```
    def as_json
      Souffle::RecipeRepresenter.new(self).to_json
    end
```

Unfortunately, the json now includes the old naming (recipeUrl800x600). Is it somehow possible to keep an alias from parsing to serialization?

**Comment by apotonick** [comment]
Does the `RecipeRepresenter` have the `:as` option, or not?
