### ISSUE TITLE
Documentation links hard to find on the trailblazer docs site

### ISSUE THREAD

**Issue by sbwoodside** [trailblazer/representable#221]
The (internal) documentation links to the various subpages e.g. Getting Started, API, etc. are not visible "[above the fold](https://en.wikipedia.org/wiki/Above_the_fold)" and are not clearly connected to the content. See screen shots.

<img width="1135" alt="screen shot 2017-06-28 at 13 51 31" src="https://user-images.githubusercontent.com/47834/27652416-a01414f2-5c09-11e7-9ce9-01310bcdd957.png">
<img width="1132" alt="screen shot 2017-06-28 at 13 51 42" src="https://user-images.githubusercontent.com/47834/27652417-a21ab850-5c09-11e7-862a-403a7c629ce5.png">

**Comment by apotonick** [comment]
What do you suggest to make it simpler? I thought a lot about it - maybe
move the "active" section up in the sidebar?

Thanks.

BTW: the Representable docs need a makeover.

**Comment by sbwoodside** [comment]
The left side titles could collapse, i.e. only the ones that are currently displayed in bold and all caps would be visible by default, and then clicking on one would reveal the subsections. That would probably allow all of the major sections to be visible and ensure that the current section/subsection is visible.

Another great idea that AWS docs use (see e.g. http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-public-data-sets.html which I just chose at random) is to have Previous and Next links at the bottom of each page.

A lot of the docs could use a makeover. One thing that I've missed for Representable is an example for Rails that shows all of the major methods (index, show, create, update, delete).

**Comment by apotonick** [comment]
The collapsing sections is indeed a good idea, I remember a pull request about that. But now Trailblazer has a paid frontend developer haha!

Thanks for the `Previous/Next` link/idea, that's a pretty awesome idea. As soon as we actually _have_ presentable pages (like the guides) this will make a lot of sense. Thanks again.

Example apps are coming, and the TRB2 book is something I started thinking about. We actually improved our doc tools a lot in the past 3 months and allocate more and more time for rewriting (and restructuring, which is the actual work!) - I'm confident by the end of summer (northern hemisphere) there should be most gems covered, and some neat sample apps with guides.

Have you seen the TRB book? We discuss Representable in the last 2 chapters.

**Comment by sbwoodside** [comment]
Great, I'm glad I was able to offer useful ideas.

I haven't seen the book. Thanks for making me aware of it. Does it offer more detail on Representable than the docs?

**Comment by apotonick** [comment]
Check trb.to - we have a new accordion sidebar now! :fireworks:

**Comment by sbwoodside** [comment]
Looks great
