### ISSUE TITLE
XML Encoding?

### ISSUE THREAD

**Issue by kraflab** [trailblazer/representable#226]
Let me know if I'm missing something, but I don't see a way to change the way xml is encoded.

Right now a string like `ü` becomes `&#xFC;` when `to_xml` is called.

This could be changed by adding an encoding option to the `to_xml` call and then changing the encoding of the nokogiri document created here: https://github.com/trailblazer/representable/blob/master/lib/representable/xml.rb#L47

I think either way that line should have `||=` instead of `=`, since it's ostensibly an option being passed to the method, but it gets immediately overridden.

```ruby
    def to_node(options={})
      options[:doc] = Nokogiri::XML::Document.new # Why is this not ||= ?
      root_tag = options[:wrap] || representation_wrap(options)

      create_representation_with(Node(options[:doc], root_tag.to_s), options, Binding)
    end
```

I'd be happy to write up a pr for this if it's wanted.

**Comment by apotonick** [comment]
Sounds good to me. Strange, we have lots of `ü` in our XML and it was fine so far - maybe a global Ruby setting is the problem?

BTW, I'm planning a massive rewrite/simplification of Representable, I already started replacing Nokogiri with Oga (which is a million times simpler and obviously faster, oh, and no `Building native extensions for the next 12 minutes...`). :stuck_out_tongue_winking_eye:

**Comment by kraflab** [comment]
PR: https://github.com/trailblazer/representable/pull/227

Good luck with your rewrite :+1:

**Comment by apotonick** [comment]
I ran into the problem myself! How embarrassing. For now, what I did was

```ruby
def to_node(options={})
  options[:doc] = Nokogiri::XML::Document.new # DISCUSS: why do we need a fresh Document here?
  options[:doc].encoding= "UTF-8"
```
