### ISSUE TITLE
Bug in dependency package declarative-option update

### ISSUE THREAD

**Issue by beruic** [trailblazer/representable#241]
Please have a look at https://github.com/apotonick/declarative-option/issues/6.

There seem to be a regression in `declarative-option` 0.1.1.

**Comment by yogeshjain999** [comment]
Thanks for reporting it @beruic!

We've yanked `declarative-option-0.1.1` and published a separate gem, [trailblazer-option](https://github.com/trailblazer/trailblazer-option) with better support for ruby-3 as mentioned [here](https://github.com/apotonick/declarative-option/issues/6#issuecomment-801098877). This will be released in `representable-3.1.0` 🍻
