### ISSUE TITLE
Nested keys within hash are getting mutated

### ISSUE THREAD

**Issue by yogeshjain999** [trailblazer/representable#242]
[Conversion](https://github.com/trailblazer/representable/blob/be5639501b9827ecaf7879b9de62b589b85b9e14/lib/representable/hash/conversion.rb#L15) module is mutating nested keys within given hash to string always.
For example, reform has a test case for populating nested property in [here](https://github.com/trailblazer/reform/blob/d1db398ca4d0d097a0c4840c9847d9e33a11463c/test/populator_skip_test.rb#L20). It fails when we upgrade `representable` to `3.1.0`

**Comment by apotonick** [comment]
Any example or test case? :beers:

**Comment by yogeshjain999** [comment]
Yes, I created a demo branch in reform and pointed it to `representable` master.

https://github.com/trailblazer/reform/compare/master...yogeshjain999:representable-bug

Failing test case in reform - [test/populator_skip_test.rb](https://github.com/yogeshjain999/reform/blob/d1db398ca4d0d097a0c4840c9847d9e33a11463c/test/populator_skip_test.rb#L18)
Test run - https://github.com/yogeshjain999/reform/runs/2202613294

BTW, I also had to `require "representable"` explicitly as I was getting an exception 

```ruby
uninitialized constant Representable::Decorator::Cached
```

PR causing undefined constant issue - https://github.com/trailblazer/representable/pull/235 ([this line](https://github.com/trailblazer/representable/pull/235/files#diff-cf210697b9d0f1f1c68bde404157f976584dff4f011a656262443ecde0092611L1))
PR causing mutation issue - https://github.com/trailblazer/representable/pull/237

**Comment by seuros** [comment]
Interesting !  Should we drop the conversion and move to symbols only ?
If i remember correctly , i changed it because a Rails version stopped using hashwithindifferentaccess in some part of the code.

**Comment by yogeshjain999** [comment]
Agree, we should only convert top level keys. Can we also drop `3.1.0` release commit as there is no gem published with it ?

**Comment by apotonick** [comment]
Sure, feel free to delete the tag, @yogeshjain999
