### ISSUE TITLE
Custom writer: method is not invoked or not invoked correctly

### ISSUE THREAD

**Issue by PJUllrich** [trailblazer/representable#251]
I try to use a custom [writer](http://trailblazer.to/2.0/gems/representable/3.0/function-api.html#writer) method to set custom properties, but it is simply not invoked during rendering. I tested it with the following setup and couldn't get it to invoke the writer method. Is this is a bug, or am I doing something wrong? Please advise.

Let's say that I have the following Representer:
```ruby
class TestRepresenter < ::Representable::Decorator
    include Representable::JSON
    
    property :p_1, as: :one
    property :p_2, writer: ->(represented:, doc:, **) { doc[:p_2] = represented.one }
end
```

And invoke it with the following:
```ruby
data = {"one": "property_one"}.to_json
TestRepresenter.new(OpenStruct.new).from_json(data)

# What I expected:
=> #<OpenStruct p_1="property_one" p_2="property_one">
# What I got:
=> #<OpenStruct p_1="property_one">
```
Then it does not set the `p_2` property. 

1. Is this intended? If yes, how can I **always** set the `p_2` property, even when it is not represented in the input?

I also tested it with a "complete" input:
```ruby
data = {"one": "property_one", "p_2": "property_two"}.to_json
TestRepresenter.new(OpenStruct.new).from_json(data)

# What I expected:
=> #<OpenStruct p_1="property_one" p_2="property_one">
# What I got:
=> #<OpenStruct p_1="property_one" p_2="property_two">
```
In this case, I expected the Representer to invoke the custom `writer` method an overriding `p_2` with the value of `one`, but it simply parses the `p_2` input and doesn't invoke the `writer` method at all. 

2. Again, if this is intended, how can I override the `p_2` property with a custom writer method?

These are my dependency versions:
```
    representable (3.1.1)
      declarative (< 0.1.0)
      trailblazer-option (>= 0.1.1, < 0.2.0)
      uber (< 0.2.0)
```

**Comment by yogeshjain999** [comment]
@PJUllrich `:writer` is used when rendering (`to_json`) and `:reader` is used when parsing (`from_json`).

So in your example, you want to override values while parsing.

```ruby
class TestRepresenter < ::Representable::Decorator
  include Representable::JSON
    
  property :p_1, as: :one
  property :p_2, reader: ->(represented:, doc:, **) { doc[:p_2] = represented.p_1 } # Using `p_1` instead of `one`
end
```

**Comment by PJUllrich** [comment]
Ah I see! Sorry, then I understood that the wrong way. Thanks for the clarification!
