### ISSUE TITLE
Can't activate multi_json on (>= 1.14.1), already activated multi_json-1.11.3

### ISSUE THREAD

**Issue by fahadbinashraf** [trailblazer/representable#254]
Hi,

I have a legacy Rails project which recently broke when I did a fresh bundle install.
The project uses the "google-api-client" gem which has this gem (representable) as a dependency and now with the latest version of representable I get this error:

```bash
can't activate multi_json (>= 1.14.1), already activated multi_json-1.11.3. Make sure all dependencies are added to Gemfile.
```
For my case, this is because, in the latest version of representable, the multi_json dependency is defined in the [json.rb](https://github.com/trailblazer/representable/blob/dd499610f7442c30169f51f270ba5fa2252d2bad/lib/representable/json.rb) file instead of the gemfile and I have some other gems that also use multi_json but only the older versions so I couldn't fix its version in my project gem file instead I had to set representable to the old version (3.0.4) in my own project's gem file to resolve my issue but it took me a lot of time to figure it all out.

So, My concern is, shouldn't this dependency be defined in the gem or gem specs file? which may resolve this kind of issue?

I hope I was able to explain it well enough.

Thank you for reading.

Cheers,
Fahad

**Comment by erikhSSI** [comment]
I had to add `gem "multi_json", '>= 1.14.1'` to my Gemfile to avoid the error.  But this should be in representable's gemspec.

The offending line is in

representable (3.1.1) lib/representable/json.rb:1:in `<top (required)>'

```
gem "multi_json", '>= 1.14.1'
```

**Comment by fahadbinashraf** [comment]
Thank you @yogeshjain999 for the clarification and @erikhSSI for the solution.
